# Generated by Django 3.0 on 2023-07-21 16:04
from django.apps import apps as global_apps
from django.db import migrations


def transfert_donnees_profiles(apps, schema_editor):
    New_profile = apps.get_model("profiles", "Profile")
    try:
        Old_profile = apps.get_model("oc_lettings_site", "Profile")
    except LookupError:
        return

    New_profile.objects.bulk_create(
        New_profile(id=profile.id,
                    favorite_city=profile.favorite_city,
                    user_id=profile.user_id)
        for profile in Old_profile.objects.all()
    )


class Migration(migrations.Migration):
    operations = [
        migrations.RunPython(transfert_donnees_profiles,
                             migrations.RunPython.noop),
    ]

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    if global_apps.is_installed("oc_lettings_site"):
        dependencies.append(("oc_lettings_site", "0002_auto_20230721_1800"))
