# Generated by Django 3.0 on 2023-07-20 15:47
from django.apps import apps as global_apps
from django.db import migrations


def transfert_donnees(apps, schema_editor):
    New_letting = apps.get_model("lettings", "Letting")
    New_address = apps.get_model("lettings", "Address")
    try:
        Old_letting = apps.get_model("oc_lettings_site", "Letting")
        Old_address = apps.get_model("oc_lettings_site", "Address")
    except LookupError:
        return

    New_letting.objects.bulk_create(
        New_letting(id=letting.id,
                    title=letting.title,
                    address_id=letting.address_id)
        for letting in Old_letting.objects.all()
    )

    New_address.objects.bulk_create(
        New_address(id=address.id,
                    number=address.number,
                    street=address.street,
                    city=address.city,
                    state=address.state,
                    zip_code=address.zip_code,
                    country_iso_code=address.country_iso_code)
        for address in Old_address.objects.all()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(transfert_donnees, migrations.RunPython.noop),
    ]

    if global_apps.is_installed("oc_lettings_site"):
        dependencies.append(("oc_lettings_site", "0001_initial"))
