version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.6
    steps:
      - checkout
      - run:
          name: create venv
          command: python -m venv venv
      - run:
          name: active venv
          command: source venv/bin/activate
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: linting
          command: flake8
      - run:
          name: testing
          command: pytest --cov

  dockerize:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: login to Docker
          command: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: build docker image
          command: docker build -t $DOCKER_USER/oc-lettings:$CIRCLE_SHA1 .
      - run:
          name: push docker image
          command: docker push $DOCKER_USER/oc-lettings:$CIRCLE_SHA1
      - run:
          name: run Docker-compose
          command: docker-compose up

  deployment:
    docker:
      - image: cimg/base:stable
    executor: python/default
    steps:
      - checkout
      - run:
          name: collect static files
          command: python manage.py collectstatic
      - run:
          name: deployment
          command: curl -X GET $RENDER_URL

workflows:
  build-dockerize-deploy:
    jobs:
      - build_and_test
      - dockerize:
          requires:
            - build_and_test
          # filters:
            # branches:
              # only: main
      - deployment:
          requires:
            - build_and_test
            - dockerize
          # filters:
            # branches:
              # only: main