version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.6
    steps:
      - checkout
      - run:
          name: compilation
          command: |
            python -m venv venv
            venv/Scripts/activate
            pip install -r requirements.txt
      - run:
          name: linting
          command: flake8
      - run:
          name: testing
          command: pytest --cov

