version: 2.1
orbs:
  docker: circleci/docker@2.2.0

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.6
    steps:
      - checkout
      - run:
          name: create venv
          command: python -m venv venv
      - run:
          name: active venv
          command: source venv/bin/activate
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: linting
          command: flake8
      - run:
          name: testing
          command: pytest --cov

  dockerize:
    docker:
      - image: docker:latest
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: build docker image
          command: docker build -t $DOCKER_IMAGE_NAME .
      - run:
          name: tag docker image
          command: docker tag $DOCKER_IMAGE_NAME:$CIRCLE_SHA1 $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$CIRCLE_SHA1
      - run:
          name: push docker image
          command: docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$CIRCLE_SHA1
      - run:
          name: run Docker-compose
          command: docker-compose up

workflows:
  build-dockerize-deploy:
    jobs:
      - build_and_test
      - dockerize:
          requires:
            - build_and_test
          filters:
            branches:
              only: main