version: 2.1
orbs:
  docker: circleci/docker@2.2.0

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.6
    steps:
      - checkout
      - run:
          name: compilation
          command: |
            python -m venv venv
            ./venv/Scripts/activate
            pip install -r requirements.txt
      - run:
          name: linting
          command: flake8
      - run:
          name: testing
          command: pytest --cov

  dockerize:
    docker:
      - image: cimg/python:3.10.6
    steps:
      - setup_remote_docker
      - checkout
      - docker/build:
          image: $DOCKER_IMAGE_NAME
          tag: $CIRCLE_SHA1
          registry: $DOCKER_REGISTRY
      - docker/push:
          image: $DOCKER_IMAGE_NAME
          tag: $CIRCLE_SHA1
          registry: $DOCKER_REGISTRY
      - docker/pull:
          images: $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$CIRCLE_SHA1
      - run:
          name: run Docker-compose
          command: docker-compose up

workflows:
  build-dockerize-deploy:
    jobs:
      - build_and_test
      - dockerize:
          requires:
            - build_and_test
          filters:
            branches:
              only: main